DELIMITER //

USE check
CREATE EVENT event1
	ON SCHEDULE EVERY 1 MINUTE
	DO
		SELECT COUNT(*) INTO @nr_rows FROM log;
		IF @nr_rows >= 95 THEN
			DELETE FROM log ORDER BY date ASC limit 10;
		END IF;

DELIMITER ;
