#!/bin/bash
ZONE=$(grep -Po '.{1,}(?=.daan-lemmens.sb.uclllabs.be)' <<< "$1")
echo $ZONE
POL=$(cut -d. -f2 <<< "$1")
echo $POL
P1=$(cut -d. -f1 <<< "$1")
echo $P1
ZONEFILE=$(cut -d. -f2- <<< "$1")
echo $ZONEFILE
SEARCH='^'"$P1"'\s'
echo $SEARCH
EXIST=$(grep -P "$SEARCH" /etc/bind/zones/db."$ZONEFILE" | wc -l)
echo $EXIST
if [ "$EXIST" -gt  0 ]; then
	cp -r /var/www/html/.index_template /var/www/html/"$ZONE"
	sed "s/placeholder/$ZONE/g" /var/www/html/.index_template/index.html > /var/www/html/"$ZONE"/index.html
	sed "s/placeholder/$ZONE/g" /etc/apache2/sites-available/.vhost_template_http.conf > /etc/apache2/sites-available/"$ZONE".conf
	a2ensite "$ZONE".conf
	systemctl reload apache2

else
	echo "Sorry, this zone doesn't exist. OR record doesn't exist in this zone."
	exit 1
fi


#ZONE		=	name of vhost	=> eg.		test.daan-lemmens.sb.uclllabs.be	=> 	ZONE=test
#POL		=	daan-lemmens
#PI		=	test
#ZONEFILE	=	daan-lemmens.sb.uclllabs.be		(zonefile of dns)
#EXIST		=	telt het aantal lines waardat bv test in voorkomt
